In [27]:
import GPy
import optuna
import numpy as np
from numpy.linalg import inv
from numpy.linalg import norm
import sys
    

seed = 123
np.random.seed(seed=seed)

In [51]:
n = 1000
sigma2 = 0.01
a = np.ones(n).reshape((n, 1))
K = np.ones((n, n)) + np.identity(n) * sigma2

In [52]:
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [53]:
K

array([[1.01, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [1.  , 1.01, 1.  , ..., 1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.01, ..., 1.  , 1.  , 1.  ],
       ...,
       [1.  , 1.  , 1.  , ..., 1.01, 1.  , 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 1.01, 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 1.  , 1.01]])

In [54]:
a.T.dot(K).dot(a)

array([[1000010.]])

In [55]:
ik = inv(K)
ik

array([[99.900001, -0.099999, -0.099999, ..., -0.099999, -0.099999,
        -0.099999],
       [-0.099999, 99.900001, -0.099999, ..., -0.099999, -0.099999,
        -0.099999],
       [-0.099999, -0.099999, 99.900001, ..., -0.099999, -0.099999,
        -0.099999],
       ...,
       [-0.099999, -0.099999, -0.099999, ..., 99.900001, -0.099999,
        -0.099999],
       [-0.099999, -0.099999, -0.099999, ..., -0.099999, 99.900001,
        -0.099999],
       [-0.099999, -0.099999, -0.099999, ..., -0.099999, -0.099999,
        99.900001]])

In [56]:
a.T.dot(ik).dot(a)

array([[0.99999]])

In [57]:
ik.dot(a)

array([[0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.00099999],
       [0.000

In [58]:
norm(ik, ord=2)

100.00000000024492

In [59]:
norm(ik, ord='fro')

3160.696125856357

In [60]:
norm(ik, ord='nuc')

99900.00099998977

In [61]:
norm(ik, ord=-2)

0.0009999900006142303

In [62]:
norm(a)

31.622776601683793

In [63]:
norm(ik.dot(a))

0.0316224603815685

In [64]:
norm(a) * norm(ik.dot(a))

0.999990000241937